/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gpi.core.gpiproyecto.views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
/**
 *
 * @author oscar
 */
public class PrincipalPage extends javax.swing.JFrame {

	/**
	 * Creates new form PrincipalPage
	 */
	public PrincipalPage() {
		initComponents();
		menu();
	}
	
	public void menu(){
			JMenuBar menuBar;
			JMenu menu, submenu;
			JMenuItem menuItem;

			//Create the menu bar.
			menuBar = new JMenuBar();

			//Build the first menu.
			menu = new JMenu("Modulos");	
			menuBar.add(menu);
			
		
			//itesm
			submenu = new JMenu("Materia prima");
			menuItem = new JMenuItem("Crear",
                         KeyEvent.VK_T);
			menuItem.addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					System.out.println("hola mundo");	
				}
			});

			submenu.add(menuItem);
			menu.add(submenu);
			menu.addSeparator();
	
			//crearmos el menu
			submenu = new JMenu("Productos");
			//creamos el item para el submenu
			menuItem = new JMenuItem("Crear",
                         KeyEvent.VK_T);
			menuItem.addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					//aqui llamariamos los internal frame
					System.out.println("hola mundo");	
				}
			});
			//agregamos el primer submenu
				submenu.add(menuItem);
			//creamos otro item para el submenu
				menuItem = new JMenuItem("listado de productos",
                         KeyEvent.VK_T);
			menuItem.addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					JInternalProductos productos = new JInternalProductos();
					jDesktopMaster.add(productos);
					productos.show();
				}
			});

			//agregamos el segundo sumenu
			submenu.add(menuItem);
			//agregamos el submenu al menu principal papa
			menu.add(submenu);
			//agreamos separador
			menu.addSeparator();
			
			
			
			menuItem = new JMenuItem("Reporte 1",
                         KeyEvent.VK_T);
			menuItem.addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					System.out.println("hola mundo");	
				}
			});
			submenu = new JMenu("Reportes");
			submenu.add(menuItem);
			menu.add(submenu);


			this.setJMenuBar(menuBar);
	}
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopMaster = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopMasterLayout = new javax.swing.GroupLayout(jDesktopMaster);
        jDesktopMaster.setLayout(jDesktopMasterLayout);
        jDesktopMasterLayout.setHorizontalGroup(
            jDesktopMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        jDesktopMasterLayout.setVerticalGroup(
            jDesktopMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopMaster)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopMaster)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PrincipalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PrincipalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PrincipalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PrincipalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PrincipalPage().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopMaster;
    // End of variables declaration//GEN-END:variables

}
